version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest  # 👈 Make sure this matches the tag in GitHub Actions

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
