POST http://localhost:8080/exam/question
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDI3Mjc5MzksIm9yZ2FuaXNhdGlvbl9pZCI6IjY3ZGM1NDc0NTYwNTg1NzY3NjcyNWQ4NyIsInJvbGUiOiJTVFVERU5UIiwidXNlcl9pZCI6IjY3ZGU5OTYzNzc1Y2Q4YTBkMDdlZjgwNyJ9.NIMVz7WTPUXR6lq1nBZTQXdoRwaEayGMlpiRuQURBUY

{
  "exam_id": "67de99a9775cd8a0d07ef808",
  "question_text": "What2222aa is the output of fmt.Println(2 + 2)?",
  "options": ["32", "42a", "15"],
  "correct_answers": ["42a"],
  "is_multi_select": false
}
