POST http://localhost:8080/exam/question
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0MDcxMTYwMywiaXNfYWRtaW4iOmZhbHNlLCJ1c2VyX2lkIjoiNjdiZmQ1MWZmZDhjYjY5NTc1ZmY3ZGY5In0.dQJxE3i59DEpB7-4QRfJM6izVpnjmWGAcdkHNJFadJk

{
  "exam_id": "67bf19a3394d3cf03ee75fd2",
  "question_text": "What is the output of fmt.Println(2 + 2)?",
  "options": ["3", "4", "5"],
  "correct_answers": [1],
  "is_multi_select": false
}

