POST http://localhost:8080/exam/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lMXFAZXhhbXBsZS5jb20iLCJleHAiOjE3NDA3MjkxMjEsImlzX2FkbWluIjpmYWxzZSwidXNlcl9pZCI6IjY3YzAwMjI5MGNlOTE0ZTM5ZWU4MzA4ZCJ9.Bdr6zYaxLPhFKdeHIgW_oBOEumPusyh847IozA-kccU

{
  "title": "Golang Advanced Exam",
  "description": "An exam covering advanced concepts in Golang, including concurrency and design patterns.",
  "duration": 90,
  "valid_from": "2025-02-21T10:00:00Z",
  "valid_till": "2025-02-21T11:30:00Z",
  "max_question": 50
}
