GET http://localhost:8080/user/students
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyNTgwOTc2LCJvcmdhbmlzYXRpb25faWQiOiI2N2RjNTQ3NDU2MDU4NTc2NzY3MjVkODciLCJyb2xlIjoiQURNSU4iLCJ1c2VyX2lkIjoiNjdkYzU0YzA1NjA1ODU3Njc2NzI1ZDg4In0.gfxiPh-IG3PjnVE6zq7jJIL8mdkkPHRiaEyVXt4JipE