GET http://localhost:8080/exam?id=67de99a9775cd8a0d07ef808
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDI3MjgwNzksIm9yZ2FuaXNhdGlvbl9pZCI6IjY3ZGM1NDc0NTYwNTg1NzY3NjcyNWQ4NyIsInJvbGUiOiJTVFVERU5UIiwidXNlcl9pZCI6IjY3ZGU5OTYzNzc1Y2Q4YTBkMDdlZjgwNyJ9.FdD-P_1Vu7FFYB-PeubLDz9HOcmhBjGBBvWFrXBi3YU