name: Deploy Lambda via CloudFormation

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to `main` branch

jobs:
  deploy:
    name: Build & Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21  # Adjust to your Go version

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main main.go
          zip my-lambda.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Update to your AWS region (e.g., Mumbai)

      - name: Upload Lambda ZIP to S3
        run: |
          aws s3 cp my-lambda.zip s3://secure-exam-lambda-bucket/

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name secure-exam-stack \
            --template-file cloudformation.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaS3Bucket=secure-exam-lambda-bucket \
              LambdaS3Key=my-lambda.zip

      - name: Verify Deployment
        run: |
          aws cloudformation describe-stacks --stack-name secure-exam-stack
